name: Node.js CI
on: [deployment_status]
jobs:
  run_e2e_test:
    name: Run E2E test with Playwright
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run e2e-test
        env:
          TARGET_URL: ${{github.event.deployment_status.target_url}}
